alter table public.bank_connections
  add column provider_authorization_id text,
  add column provider_session_id text,
  add column provider_state text,
  add column provider_psu_id_hash text,
  add column provider_metadata jsonb not null default '{}'::jsonb;

create unique index bank_connections_provider_authorization_unique
  on public.bank_connections (user_id, provider, provider_authorization_id)
  where provider_authorization_id is not null;

create unique index bank_connections_provider_session_unique
  on public.bank_connections (user_id, provider, provider_session_id)
  where provider_session_id is not null;

create unique index bank_connections_provider_state_unique
  on public.bank_connections (provider, provider_state)
  where provider_state is not null;

comment on column public.bank_connections.provider_authorization_id is
  'External Enable Banking authorization identifier returned by POST /auth.';
comment on column public.bank_connections.provider_session_id is
  'External Enable Banking session identifier returned by POST /sessions.';
comment on column public.bank_connections.provider_state is
  'Opaque callback state generated by the app and validated before linking.';
comment on column public.bank_connections.provider_psu_id_hash is
  'Enable Banking hash of the app-provided PSU identifier.';
comment on column public.bank_connections.provider_metadata is
  'Small provider-specific operational metadata for consent management.';
